---
- name: Create User
  hosts: 10.15.2.4
  tasks:
    - name: Add new user
      win_user:
       name: winrm
       password: 12qwaszx!@QWASZX
       user_cannot_change_password: yes
       password_never_expires: yes 
       state: present