---
- name: Install Dsc Modules
  hosts: all
  vars:
   ansible_shell_type: powershell
  tasks:
  - name: Install PSDesiredStateConfiguration
    win_psmodule:
     name: PSDesiredStateConfiguration
     state: present
  
  - name: Install xWebAdministration
    win_psmodule:
     name: xWebAdministration
     state: present

  - name: Install ComputerManagementDsc
    win_psmodule:
     name: ComputerManagementDsc
     state: present

  - name: Create CRLDP Folder
    win_dsc:
     resource_name: File
     DestinationPath: C:\crldp
     type: directory

  - name: Create CRLDP SMB Share
    win_share:
     name: CRLDP
     path: c:\crldp
     list: yes
     full: Administrators
     read: everyone

  - name: Install Web-Server
    win_feature:
     name: Web-Server
     state: present
     include_sub_features: yes
     include_management_tools: yes 
    register: iis_install

  - name: Install .NET45
    win_feature:
     name: Web-Asp-Net45
     state: present
     include_sub_features: yes
     include_management_tools: yes
    register: net45_install

  - name: Remove Default Site
    win_dsc:
     resource_name: xWebsite
     state: stopped
     name: 'Default Web Site'
     ensure: absent

  - name: Create CRLDP
    win_dsc:
     resource_name: xWebsite
     state: started
     name: crldp
     physicalpath: c:\crldp
     ensure: present
     bindinginfo:
     - Protocol: http
       port: 80
       ipaddress: '*'
     authenticationinfo:
      anonymous: yes
      basic: no
      digest: no
      windows: no

  - name: CRLDP Browse
    win_dsc:
     resource_name: xWebConfigProperty
     websitepath: iis:\sites\crldp
     ensure: present
     filter: 'system.webServer/directoryBrowse'
     propertyname: enabled
     value: true

  - name: Hide web.config
    win_dsc:
     resource_name: file
     ensure: present
     path: c:\crldp\web.config
     attributes: hidden