---
- name: Install Dsc Modules
  hosts: all
  vars:
   ansible_shell_type: powershell
   #ansible_become: yes
   #ansible_become_method: runas
   #ansible_become_user: .\xadmin
   #ansible_become_password: 12qwaszx!@QWASZX
   #ansible_become_flags: logon_type=batch
  tasks:
  - name: Install PSDesiredStateConfiguration
    win_psmodule:
     name: PSDesiredStateConfiguration
     state: present
  
  - name: Install xWebAdministration
    win_psmodule:
     name: xWebAdministration
     state: present

  - name: Install ComputerManagementDsc
    win_psmodule:
     name: ComputerManagementDsc
     state: present

  - name: Create CRLDP Folder
    win_dsc:
     resource_name: File
     DestinationPath: C:\crldp
     type: directory

  - name: Create CRLDP SMB Share
    win_share:
     name: CRLDP
     path: c:\crldp
     list: yes
     full: Administrators
     read: everyone

  - name: Install Web-Server
    win_feature:
     name: Web-Server
     state: present
     include_sub_features: yes
     include_management_tools: yes 
    register: iis_install

  - name: Install .NET45
    win_feature:
     name: Web-Asp-Net45
     state: present
     include_sub_features: yes
     include_management_tools: yes
    register: net45_install

  - name: Remove Default Site
    win_dsc:
     resource_name: xWebsite
     state: stopped
     name: 'Default Web Site'
     ensure: absent

  - name: Create CRLDP
    win_dsc:
     resource_name: xWebsite
     state: started
     name: crldp
     physicalpath: c:\crldp
     ensure: present
     bindinginfo:
     - Protocol: http
       port: 80
       ipaddress: '*'
     authenticationinfo:
      anonymous: yes
      basic: no
      digest: no
      windows: no

  - name: CRLDP Browse
    win_dsc:
     resource_name: xWebConfigProperty
     websitepath: iis:\sites\crldp
     ensure: present
     filter: 'system.webServer/directoryBrowse'
     propertyname: enabled
     value: true

  - name: Hide web.config
    win_dsc:
     resource_name: file
     ensure: present
     destinationpath: c:\crldp\web.config
     attributes: hidden

  - name: copy initial crls
    win_shell: |
     $crl1 = "http://crldp.kdrodemo.com/kdemo-RootCA(1).crl"
     $crl1output = "kdemo-RootCA(1).crl"
     $cert2 = "http://crldp.kdrodemo.com/kdemo-ca01.kdr-demo.com_kdemo-RootCA(0-1).crt"
     $cert2output = "kdemo-ca01.kdr-demo.com_kdemo-RootCA(0-1).crt"
     $cert3 = "http://crldp.kdrodemo.com/kdemo-ca01.kdr-demo.com_kdemo-RootCA(1-0).crt"
     $cert3output = "kdemo-ca01.kdr-demo.com_kdemo-RootCA(1-0).crt"
     $cert4 = "http://crldp.kdrodemo.com/kdemo-ca01.kdr-demo.com_kdemo-RootCA(1).crt"
     $cert4output = "kdemo-ca01.kdr-demo.com_kdemo_RootCA(1).crt"
     $cert5 = "http://crldp.kdrodemo.com/kdemo-ca03.kdr-demo.com_kdemo-SubCA.crt"
     $cert5output = "kdemo-ca03.kdr-demo.com_kdemo-SubCA.crt"
     $crl3 = "http://crldp.kdrodemo.com/kdemo-SubCA.crl"
     $crl3output = "kdemo-SubCA.crl"
     Invoke-WebRequest -Uri $crl1 -OutFile c:\crldp\$crl1output
     Invoke-WebRequest -Uri $cert2 -OutFile c:\crldp\$cert2output
     Invoke-WebRequest -Uri $cert3 -OutFile c:\crldp\$cert3output
     Invoke-WebRequest -Uri $cert4 -OutFile c:\crldp\$cert4output
     Invoke-WebRequest -Uri $cert5 -OutFile c:\crldp\$cert5output
     Invoke-WebRequest -Uri $crl3 -OutFile c:\crldp\$crl3output