---
- name: Check Domain Controller Configurations
  hosts: all
  vars:
   ansible_shell_type: powershell

  tasks:
  - name: Install ActiveDirectoryDsc
    win_psmodule:
     name: ActiveDirectoryDsc
     state: present

  - name: Install ActiveDirectoryCSDsc
    win_psmodule:
     name: ActiveDirectoryCSDsc

  - name: Install ComputerManagementDsc
    win_psmodule:
     name: ComputerManagementDsc

  - name: Install DnsServerDsc
    win_psmodule:
     name: DnsServerDsc
     state: present

  - name: Install NetworkingDsc
    win_psmodule:
     name: NetworkingDsc
     state: present

  - name: Install PSDesiredStateConfiguration
    win_psmodule:
     name: PSDesiredStateConfiguration
     state: present


  - name: Enable TLS 1.2 Registry - Enabled
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
     name: Enabled
     value: '1'
     type: Dword
     state: present
     
  - name: Disable TLS 1.2 Registry - DisabledByDefault
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
     name: DisabledByDefault
     value: '0'
     type: Dword
     state: present

  - name: Enable TLS 1.2 Registry - Enabled
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
     name: Enabled
     value: '1'
     type: Dword
     state: present

  - name: Configure DNS Server Forwarders
    win_dsc:
     resource_name: DnsServerForwarder
     issingleinstance: yes
     ipaddresses: 10.1.5.7, 10.5.1.4, 8.8.8.8, 1.1.1.1
     useroothint: no
     dependson: '[WindowsFeature]Dns'

  - name: Configure DNS Forward Zones
    win_dsc:
     resource_name: DnsServerADZone
     name: ocsp.defkdrodemo.com
     dynamicupdate: NonSecureAndSecure
     replicationscope: Forest
     state: present

  - name: Add entry in DNS Zone
    win_dns_record:
     name: "10.10.1.6"
     type: "PTR"
     value: "*"
     state: present

     
  

  