---
- name: Check Domain Controller Configurations
  hosts: all
  vars:
   ansible_shell_type: powershell

  tasks:
  - name: Enable TLS 1.2 Registry - Enabled
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
     name: Enabled
     data: 1
     type: Dword
     state: absent
     
  - name: Disable TLS 1.2 Registry - DisabledByDefault
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
     name: DisabledByDefault
     data: 0
     type: Dword
     state: absent

  - name: Enable TLS 1.2 Registry - Enabled
    win_regedit:
     path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
     name: Enabled
     data: 1
     type: Dword
     state: absent

  - name: Configure DNS AD-integrated Forward Zone
    win_dsc:
     resource_name: DnsServerADZone
     name: 'ocsp.defkdrodemo.com'
     dynamicupdate: 'NonSecureAndSecure'
     replicationscope: 'Forest'
     dependson: '[WindowsFeature]Dns'
     ensure: absent
     
  - name: Add entry in DNS Zone
    win_dns_record:
     zone: "ocsp.defkdrodemo.com"
     name: "*"
     type: "A"
     value: "10.10.1.6"
     state: absent

  - name: Add Conditional Forwarder
    win_dsc:
     resource_name: DnsServerConditionalForwarder
     name: 'kdrodemo.com'
     masterservers: '10.5.10.7,10.5.10.4'
     replicationscope: 'Forest'
     dependson: '[WindowsFeature]Dns'
     ensure: absent

  - name: Remove ActiveDirectoryDsc
    win_psmodule:
     name: ActiveDirectoryDsc
     state: absent

  - name: Remove ActiveDirectoryCSDsc
    win_psmodule:
     name: ActiveDirectoryCSDsc
     state: absent

  - name: Remove ComputerManagementDsc
    win_psmodule:
     name: ComputerManagementDsc
     state: absent

  - name: Remove DnsServerDsc
    win_psmodule:
     name: DnsServerDsc
     state: absent

  - name: Remove NetworkingDsc
    win_psmodule:
     name: NetworkingDsc
     state: absent
     
  

  